name: Deploy Plotly Dashboard Test1

on:
  push:
    branches: [ main ]

env:
  PROJECT_ID: gcp-devops-376307
  SERVICE_ACCOUNT_KEY: ${{ secrets.GCP_SA_KEY }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - id: 'auth'
        name: Configure GCP credentials
        uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'
          token_format: 'access_token'
      
      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          tags: ${{ env.PROJECT_ID }}/freelancing3:${{ github.sha }}
          
      - name: Log in to GCR
        uses: docker/login-action@v1
        with:
          registry: gcr.io
          username: _json_key
          password: ${{ secrets.GCP_SA_KEY }}
          
      - name: Push Docker image to GCR
        run: |
          docker build -t gcr.io/${{ env.PROJECT_ID }}/freelancing3:${{ github.sha }} .
          docker push gcr.io/${{ env.PROJECT_ID }}/freelancing3:${{ github.sha }}
      
      - name: Deploy to Cloud Run
        run: |
          terraform init -input=true
          terraform state list
          terraform plan -var="image_tag=${{ github.sha }}"
          terraform apply -var="image_tag=${{ github.sha }}" -auto-approve
